apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-config
  namespace: kube-system
  labels:
    app: "alibaba-ccm"
    chart: "alibaba-ccm.chart"
    release: "alibaba-ccm"
    heritage: "alibaba-ccm"
data:
  special.keyid: {{ .Values.accessKey | quote }}
  special.keysecret: {{ .Values.accessSecret | quote }}
