{{- if and .Values.serviceAccount.create .Values.rbac.create }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "terway.fullname" . }}
  namespace: kube-system
  labels:
    app: {{ template "terway.name" . | quote }}
    chart: {{ template "terway.chart" . | quote }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "namespaces", "configmaps", "serviceaccounts"]
    verbs: ["get", "watch", "list", "update"]
  - apiGroups: [""]
    resources:
      - events
    verbs:
      - create
  - apiGroups: ["networking.k8s.io"]
    resources:
      - networkpolicies
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["extensions"]
    resources:
      - networkpolicies
    verbs:
      - get
      - list
      - watch
  - apiGroups: [""]
    resources:
      - pods/status
    verbs:
      - update
  - apiGroups: ["crd.projectcalico.org"]
    resources: ["*"]
    verbs: ["*"]
{{- end }}
