apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "terway.serviceAccountName" . }}
  namespace: kube-system
  labels:
    app: {{ template "terway.name" . | quote }}
    chart: {{ template "terway.chart" . | quote }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
